import type { Metadata } from "next";
import "./globals.css";
import RootBody from "./Rootbody";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RootBody>{children}</RootBody>
      </body>
    </html>
  );
}
